name: MaxMuzik Live Stream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir otomatik çalıştırma

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install FFmpeg & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install requests yt-dlp

      - name: Create Cookies File
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt
        # GitHub Secrets üzerinde YOUTUBE_COOKIES tanımlanmış olmalıdır.

      - name: Run Stream Script
        run: python maxmuzik.py
